name: prism_gradients_toolkit
description: "prism_gradients_toolkit is a Flutter package that provides beautiful, customizable gradient UI components like buttons, avatars, textfields and containers. Great for modern apps that want a vibrant, eye-catching design. Just plug and play!"
version: 0.0.1
homepage: https://github.com/yourusername/prism_gradients_toolkit
repository: https://github.com/yourusername/prism_gradients_toolkit
issue_tracker: https://github.com/yourusername/prism_gradients_toolkit/issues

topics:
  - flutter
  - gradient
  - ui
  - widgets
  - animation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

